<?php
/**
 * @file
 * (Un)installation hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_gmap_uninstall() {
  $variables = array(
    'islandora_gmap_collapsed',
    'islandora_gmap_width',
    'islandora_gmap_height',
    'islandora_gmap_cluster_points',
    'islandora_gmap_initial_zoom',
    'islandora_gmap_min_zoom',
    'islandora_gmap_max_zoom',
    'islandora_gmap_fit_bounds',
    'islandora_gmap_api_key',
  );

  array_map('variable_del', $variables);
}
